[package]
name = "halyard_server_fn_macro_default"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/cgorski/halyard"
description = "The default implementation of the server_fn macro without a context"
version = "0.1.0"
publish = ["crates-io"]
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, default-features = true }
halyard_server_fn_macro = { workspace = true }

[features]
ssr = ["halyard_server_fn_macro/ssr"]
actix = ["halyard_server_fn_macro/actix"]
axum = ["halyard_server_fn_macro/axum"]

[package.metadata.cargo-all-features]
max_combination_size = 2
