[package]
name = "halyard_const_str_slice_concat"
version = "0.1.0"
publish = ["crates-io"]
authors = ["Greg Johnston"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/cgorski/halyard"
description = "Utilities for const concatenation of string slices."
rust-version.workspace = true
edition.workspace = true

[dependencies]
