[package]
name = "halyard_or_poisoned"
version = "0.1.0"
publish = false
authors = ["Greg Johnston"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/cgorski/halyard"
description = "Unwrap std lock guards in a semantic way."
rust-version.workspace = true
edition.workspace = true

[dependencies]
