#![forbid(unsafe_code)]

pub mod errors;

use crate::errors::HalyardConfigError;
use config::{Case, Config, File, FileFormat};
use std::{
    env::VarError,
    fs,
    net::SocketAddr,
    path::{Path, PathBuf},
    str::FromStr,
    sync::Arc,
};
use typed_builder::TypedBuilder;

/// A Struct to allow us to parse [`HalyardOptions`] from the file.
/// Not really needed, most interactions should occur with `HalyardOptions`.
#[derive(Clone, Debug, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
#[non_exhaustive]
pub struct ConfFile {
    pub halyard_options: HalyardOptions,
}

/// This struct serves as a convenient place to store details used for configuring Halyard.
/// It's used in our axum integration to generate the
/// correct path for WASM, JS, and Websockets, as well as other configuration tasks.
/// It shares keys with cargo-halyard, to allow for easy interoperability
#[derive(TypedBuilder, Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
#[non_exhaustive]
pub struct HalyardOptions {
    /// The name of the WASM and JS files generated by wasm-bindgen.
    ///
    /// This should match the name that will be output when building your application.
    ///
    /// You can easily set this using `env!("CARGO_CRATE_NAME")`.
    #[builder(setter(into))]
    pub output_name: Arc<str>,
    /// The file name (without the `.wasm` extension) of the WASM bundle inside
    /// `site_pkg_dir`, if it differs from `output_name`.
    ///
    /// `cargo-halyard` / `cargo-leptos` write `<output_name>.wasm`, so this is
    /// normally left unset. Running `wasm-bindgen` by hand produces
    /// `<output_name>_bg.wasm`, in which case set this to `"<output_name>_bg"`.
    ///
    /// This is resolved at **runtime** (see [`HalyardOptions::wasm_file_stem`]);
    /// upstream Leptos decided between the two names from a compile-time
    /// `option_env!`, so a server built by plain `cargo build` requested a
    /// file the build tool never wrote.
    #[builder(default, setter(strip_option, into))]
    #[serde(default)]
    pub wasm_file_name: Option<Arc<str>>,
    /// The path of the all the files generated by cargo-halyard.
    ///
    /// This defaults to '.' for convenience when integrating with other tools.
    #[builder(setter(into), default=default_site_root())]
    #[serde(default = "default_site_root")]
    pub site_root: Arc<str>,
    /// The path of the WASM and JS files generated by wasm-bindgen from the root of your app.
    ///
    /// By default, wasm-bindgen puts them in `pkg`.
    #[builder(setter(into), default=default_site_pkg_dir())]
    #[serde(default = "default_site_pkg_dir")]
    pub site_pkg_dir: Arc<str>,
    /// Used to configure the running environment of Halyard.
    /// Can be used to load dev constants and keys v prod,
    /// or change things based on the deployment environment.
    ///
    /// I recommend passing in `Env::try_from(&env::var("HALYARD_ENV"))?`, which is
    /// [`Env::DEV`] when the variable is not set, and an error when it is set to
    /// something else than `dev`/`development`/`prod`/`production`.
    #[builder(setter(into), default=default_env())]
    #[serde(default = "default_env")]
    pub env: Env,
    /// Provides a way to control the address halyard is served from.
    /// Using an env variable here would allow you to run the same code in dev and prod.
    ///
    /// Defaults to `127.0.0.1:3000`.
    #[builder(setter(into), default=default_site_addr())]
    #[serde(default = "default_site_addr")]
    pub site_addr: SocketAddr,
    /// The port the Websocket watcher listens on.
    /// Should match the `reload_port` in cargo-halyard (if using).
    ///
    /// Defaults to `3001`.
    #[builder(default = default_reload_port())]
    #[serde(default = "default_reload_port")]
    pub reload_port: u32,
    /// The port the Websocket watcher listens on when on the client, e.g.,
    /// when behind a reverse proxy.
    ///
    /// Defaults to match `reload_port`.
    #[builder(default)]
    #[serde(default)]
    pub reload_external_port: Option<u32>,
    /// The protocol the Websocket watcher uses on the client: `ws` in most cases, `wss` when behind
    /// a reverse https proxy.
    ///
    /// Defaults to `ws`
    #[builder(default)]
    #[serde(default)]
    pub reload_ws_protocol: ReloadWSProtocol,
    /// The path of a custom 404 Not Found page to display when statically serving content.
    ///
    /// Defaults to `site_root/404.html`.
    #[builder(default = default_not_found_path())]
    #[serde(default = "default_not_found_path")]
    pub not_found_path: Arc<str>,
    /// The file name of the hash text file generated by cargo-halyard.
    ///
    /// Defaults to `hash.txt`.
    #[builder(default = default_hash_file_name())]
    #[serde(default = "default_hash_file_name")]
    pub hash_file: Arc<str>,
    /// If `true`, hashes will be generated for all files
    /// in the `site_root` and added to their file names.
    ///
    /// Defaults to `false`.
    #[builder(default = default_hash_files())]
    #[serde(default = "default_hash_files")]
    pub hash_files: bool,
    /// The default prefix to use for server functions when generating API routes. Can be
    /// overridden for individual functions using `#[server(prefix = "...")]` as usual.
    ///
    /// This is useful to override the default prefix (`/api`) for all server functions without
    /// needing to manually specify via `#[server(prefix = "...")]` on every server function.
    #[builder(default, setter(strip_option))]
    #[serde(default)]
    pub server_fn_prefix: Option<String>,
    /// Whether to disable appending the server functions' hashes to the end of their API names.
    ///
    /// This is useful when an app's client side needs a stable server API. For example, shipping
    /// the CSR WASM binary in a Tauri app. Tauri app releases are dependent on each platform's
    /// distribution method (e.g., the Apple App Store or the Google Play Store), which typically
    /// are much slower than the frequency at which a website can be updated. In addition, it's
    /// common for users to not have the latest app version installed. In these cases, the CSR WASM
    /// app would need to be able to continue calling the backend server function API, so the API
    /// path needs to be consistent and not have a hash appended.
    ///
    /// Note that the hash suffixes is intended as a way to ensure duplicate API routes are created.
    /// Without the hash, server functions will need to have unique names to avoid creating
    /// duplicate routes. Axum will throw an error if a duplicate route is added to the router, but
    /// Actix will not.
    #[builder(default)]
    #[serde(default)]
    pub disable_server_fn_hash: bool,
    /// Include the module path of the server function in the API route. This is an alternative
    /// strategy to prevent duplicate server function API routes (the default strategy is to add
    /// a hash to the end of the route). Each element of the module path will be separated by a `/`.
    /// For example, a server function with a fully qualified name of `parent::child::server_fn`
    /// would have an API route of `/api/parent/child/server_fn` (possibly with a
    /// different prefix and a hash suffix depending on the values of the other server fn configs).
    #[builder(default)]
    #[serde(default)]
    pub server_fn_mod_path: bool,
}

impl HalyardOptions {
    /// Returns the path on disk to the generated CSS file.  This is done by joining `site_root`,
    /// `site_pkg_dir`, and the `output_name` with `.css` appended to it.
    ///
    /// # Example
    ///
    /// ```
    /// use halyard_config::HalyardOptions;
    ///
    /// let options = HalyardOptions::builder().output_name("test").build();
    /// let path = options.css_file_path();
    /// let mut ancestors = path.ancestors();
    ///
    /// assert_eq!(path.file_name().unwrap(), "test.css");
    /// ```
    pub fn css_file_path(&self) -> PathBuf {
        Path::new(&*self.site_root)
            .join(&*self.site_pkg_dir)
            .join(format!("{}.css", self.output_name))
    }

    /// Returns the path portion of the uri to the generated CSS file.  This is done by combining
    /// `site_pkg_dir` and the `output_name` with `.css` appended to it.
    ///
    /// # Example
    ///
    /// ```
    /// use halyard_config::HalyardOptions;
    ///
    /// let options = HalyardOptions::builder().output_name("test").build();
    /// let path = options.css_path();
    /// assert_eq!(path, "/pkg/test.css");
    /// ```
    pub fn css_path(&self) -> String {
        let mut path = self.site_pkg_dir_route_base();
        path.push_str(&self.output_name);
        path.push_str(".css");
        path
    }

    /// Returns the file stem of the WASM bundle: [`Self::wasm_file_name`] if
    /// set, otherwise [`Self::output_name`].
    ///
    /// # Example
    ///
    /// ```
    /// use halyard_config::HalyardOptions;
    ///
    /// let options = HalyardOptions::builder().output_name("app").build();
    /// assert_eq!(options.wasm_file_stem(), "app");
    ///
    /// let options = HalyardOptions::builder()
    ///     .output_name("app")
    ///     .wasm_file_name("app_bg")
    ///     .build();
    /// assert_eq!(options.wasm_file_stem(), "app_bg");
    /// ```
    pub fn wasm_file_stem(&self) -> &str {
        self.wasm_file_name
            .as_deref()
            .filter(|name| !name.is_empty())
            .unwrap_or(&self.output_name)
    }

    /// Returns the base route to the `site_pkg_dir` with a leading and trailing slash added as necessary.
    pub fn site_pkg_dir_route_base(&self) -> String {
        let mut path = String::new();
        // While it shouldn't start with a '/', but check anyway.
        if !self.site_pkg_dir.starts_with('/') {
            path.push('/');
        }
        path.push_str(&self.site_pkg_dir);
        if !path.ends_with('/') {
            path.push('/');
        }
        path
    }

    /// Builds the options from environment variables at **runtime**.
    ///
    /// Every option is read from `HALYARD_<NAME>`, falling back to the
    /// legacy `LEPTOS_<NAME>` so that existing `cargo-leptos` configs and
    /// deployment environments keep working (see [`halyard_env`]).
    ///
    /// Nothing here is baked in at compile time: the upstream code used
    /// `option_env!("LEPTOS_OUTPUT_NAME")` as a fallback, which meant a
    /// server binary built by plain `cargo build` rendered different asset
    /// URLs than one built by the build tool.
    fn try_from_env() -> Result<Self, HalyardConfigError> {
        let output_name = halyard_env_w_default("OUTPUT_NAME", "")?;
        if output_name.is_empty() {
            use std::io::Write;
            // `eprintln!` panics if standard error is closed; with nowhere left to
            // report the warning, it is dropped
            _ = writeln!(
                std::io::stderr(),
                "Neither HALYARD_OUTPUT_NAME nor LEPTOS_OUTPUT_NAME is set, so \
                 `output_name` is empty and the client JS/WASM URLs will be \
                 wrong. Either\n 1. pass Some(\"Cargo.toml\") to \
                 get_configuration() so it is read from \
                 [package.metadata.halyard], or\n 2. set HALYARD_OUTPUT_NAME \
                 in the server's environment (cargo-halyard / cargo-leptos do \
                 this for you)."
            );
        }
        Ok(HalyardOptions {
            output_name: output_name.into(),
            wasm_file_name: halyard_env("WASM_FILE_NAME")?.map(Into::into),
            site_root: halyard_env_w_default("SITE_ROOT", "target/site")?
                .into(),
            site_pkg_dir: halyard_env_w_default("SITE_PKG_DIR", "pkg")?.into(),
            env: env_from_str(halyard_env_w_default("ENV", "DEV")?.as_str())?,
            site_addr: halyard_env_w_default("SITE_ADDR", "127.0.0.1:3000")?
                .parse()?,
            reload_port: halyard_env_w_default("RELOAD_PORT", "3001")?
                .parse()?,
            reload_external_port: match halyard_env("RELOAD_EXTERNAL_PORT")? {
                Some(val) => Some(val.parse()?),
                None => None,
            },
            reload_ws_protocol: ws_from_str(
                halyard_env_w_default("RELOAD_WS_PROTOCOL", "ws")?.as_str(),
            )?,
            not_found_path: halyard_env_w_default("NOT_FOUND_PATH", "/404")?
                .into(),
            hash_file: halyard_env_w_default("HASH_FILE_NAME", "hash.txt")?
                .into(),
            hash_files: halyard_env_w_default("HASH_FILES", "false")?
                .parse()?,
            server_fn_prefix: env_wo_default("SERVER_FN_PREFIX")?,
            disable_server_fn_hash: env_wo_default("DISABLE_SERVER_FN_HASH")?
                .is_some(),
            server_fn_mod_path: env_wo_default("SERVER_FN_MOD_PATH")?.is_some(),
        })
    }
}

/// The environment-variable prefix used by halyard (`HALYARD_OUTPUT_NAME`, ...).
pub const ENV_PREFIX: &str = "HALYARD";
/// The legacy environment-variable prefix, accepted as a fallback so that
/// `cargo-leptos` and existing deployments keep working (`LEPTOS_OUTPUT_NAME`, ...).
pub const LEGACY_ENV_PREFIX: &str = "LEPTOS";

/// Reads the runtime environment variable `HALYARD_<name>`, falling back to
/// the legacy `LEPTOS_<name>`.
///
/// Returns `Ok(None)` if neither is set.
pub fn halyard_env(name: &str) -> Result<Option<String>, HalyardConfigError> {
    if let Some(val) = env_wo_default(&format!("{ENV_PREFIX}_{name}"))? {
        return Ok(Some(val));
    }
    env_wo_default(&format!("{LEGACY_ENV_PREFIX}_{name}"))
}

/// Like [`halyard_env`], but returns `default` if neither variable is set.
pub fn halyard_env_w_default(
    name: &str,
    default: &str,
) -> Result<String, HalyardConfigError> {
    Ok(halyard_env(name)?.unwrap_or_else(|| default.to_string()))
}

/// Returns `true` if `HALYARD_<name>` or the legacy `LEPTOS_<name>` is set
/// (to any value) in the runtime environment.
pub fn halyard_env_is_set(name: &str) -> bool {
    std::env::var_os(format!("{ENV_PREFIX}_{name}")).is_some()
        || std::env::var_os(format!("{LEGACY_ENV_PREFIX}_{name}")).is_some()
}

fn default_site_root() -> Arc<str> {
    ".".into()
}

fn default_site_pkg_dir() -> Arc<str> {
    "pkg".into()
}

fn default_env() -> Env {
    Env::DEV
}

fn default_site_addr() -> SocketAddr {
    SocketAddr::from(([127, 0, 0, 1], 3000))
}

fn default_reload_port() -> u32 {
    3001
}

fn default_not_found_path() -> Arc<str> {
    "/404".into()
}

fn default_hash_file_name() -> Arc<str> {
    "hash.txt".into()
}

fn default_hash_files() -> bool {
    false
}

fn env_wo_default(key: &str) -> Result<Option<String>, HalyardConfigError> {
    match std::env::var(key) {
        Ok(val) => Ok(Some(val)),
        Err(VarError::NotPresent) => Ok(None),
        Err(e) => Err(HalyardConfigError::EnvVarError(format!("{key}: {e}"))),
    }
}
#[cfg_attr(not(test), allow(dead_code))]
fn env_w_default(
    key: &str,
    default: &str,
) -> Result<String, HalyardConfigError> {
    match std::env::var(key) {
        Ok(val) => Ok(val),
        Err(VarError::NotPresent) => Ok(default.to_string()),
        Err(e) => Err(HalyardConfigError::EnvVarError(format!("{key}: {e}"))),
    }
}

pub const ENV_DEV_KEY_SHORT: &str = "dev";
pub const ENV_DEV_KEY_LONG: &str = "development";
pub const ENV_PROD_KEY_SHORT: &str = "prod";
pub const ENV_PROD_KEY_LONG: &str = "production";

/// An enum that can be used to define the environment Halyard is running in.
/// Setting this to the `PROD` variant will not include the WebSocket code for `cargo-halyard` watch mode.
/// Defaults to `DEV`.
#[derive(Debug, Clone, serde::Serialize, PartialEq, Eq, Default)]
pub enum Env {
    PROD,
    #[default]
    DEV,
}

fn env_from_str(input: &str) -> Result<Env, HalyardConfigError> {
    let sanitized = input.to_lowercase();
    match sanitized.as_ref() {
        ENV_DEV_KEY_SHORT | ENV_DEV_KEY_LONG => Ok(Env::DEV),
        ENV_PROD_KEY_SHORT | ENV_PROD_KEY_LONG => Ok(Env::PROD),
        _ => Err(HalyardConfigError::InvalidEnv {
            value: input.to_string(),
        }),
    }
}

impl FromStr for Env {
    type Err = ();
    fn from_str(input: &str) -> Result<Self, Self::Err> {
        env_from_str(input).or_else(|_| Ok(Self::default()))
    }
}

/// Parses `dev`, `development`, `prod` or `production`, in any case.
impl TryFrom<&str> for Env {
    type Error = HalyardConfigError;

    fn try_from(str: &str) -> Result<Self, Self::Error> {
        env_from_str(str)
    }
}

/// Parses the result of `std::env::var("HALYARD_ENV")`: an unset (or unreadable)
/// variable is the default, [`Env::DEV`].
impl TryFrom<&Result<String, VarError>> for Env {
    type Error = HalyardConfigError;

    fn try_from(input: &Result<String, VarError>) -> Result<Self, Self::Error> {
        match input {
            Ok(str) => env_from_str(str),
            Err(_) => Ok(Self::default()),
        }
    }
}

impl TryFrom<String> for Env {
    type Error = HalyardConfigError;

    fn try_from(s: String) -> Result<Self, Self::Error> {
        env_from_str(s.as_str())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Hash)]
struct EnvVisitor;

impl<'de> serde::de::Visitor<'de> for EnvVisitor {
    type Value = Env;

    fn expecting(
        &self,
        formatter: &mut std::fmt::Formatter,
    ) -> std::fmt::Result {
        write!(
            formatter,
            "a case-insensitive string of either `{ENV_DEV_KEY_SHORT}`, \
             `{ENV_DEV_KEY_LONG}`, `{ENV_PROD_KEY_SHORT}`, or \
             `{ENV_PROD_KEY_LONG}`"
        )
    }

    fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        env_from_str(v).map_err(|err| E::custom(err.to_string()))
    }
}

impl<'de> serde::Deserialize<'de> for Env {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        deserializer.deserialize_any(EnvVisitor)
    }
}

/// An enum that can be used to define the websocket protocol Halyard uses for live reloading
/// Defaults to `ws`.
#[derive(
    Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq, Eq, Default,
)]
pub enum ReloadWSProtocol {
    #[default]
    WS,
    WSS,
}

fn ws_from_str(input: &str) -> Result<ReloadWSProtocol, HalyardConfigError> {
    let sanitized = input.to_lowercase();
    match sanitized.as_ref() {
        "ws" => Ok(ReloadWSProtocol::WS),
        "wss" => Ok(ReloadWSProtocol::WSS),
        _ => Err(HalyardConfigError::InvalidReloadWsProtocol {
            value: input.to_string(),
        }),
    }
}

impl FromStr for ReloadWSProtocol {
    type Err = ();
    fn from_str(input: &str) -> Result<Self, Self::Err> {
        ws_from_str(input).or_else(|_| Ok(Self::default()))
    }
}

/// Parses `ws` or `wss`, in any case.
impl TryFrom<&str> for ReloadWSProtocol {
    type Error = HalyardConfigError;

    fn try_from(str: &str) -> Result<Self, Self::Error> {
        ws_from_str(str)
    }
}

/// Parses the result of `std::env::var("HALYARD_RELOAD_WS_PROTOCOL")`: an unset (or
/// unreadable) variable is the default, [`ReloadWSProtocol::WS`].
impl TryFrom<&Result<String, VarError>> for ReloadWSProtocol {
    type Error = HalyardConfigError;

    fn try_from(input: &Result<String, VarError>) -> Result<Self, Self::Error> {
        match input {
            Ok(str) => ws_from_str(str),
            Err(_) => Ok(Self::default()),
        }
    }
}

impl TryFrom<String> for ReloadWSProtocol {
    type Error = HalyardConfigError;

    fn try_from(s: String) -> Result<Self, Self::Error> {
        ws_from_str(s.as_str())
    }
}

/// Finds the first line of `text` that starts with `prefix`, and returns how many lines
/// come before it, and the text from its start to the end.
fn find_line_starting_with<'a>(
    text: &'a str,
    prefix: &str,
) -> Option<(usize, &'a str)> {
    let mut rest = text;
    let mut lines_before = 0_usize;
    loop {
        if rest.starts_with(prefix) {
            return Some((lines_before, rest));
        }
        (_, rest) = rest.split_once('\n')?;
        // one line per newline, so it cannot pass `text.len()`
        lines_before = lines_before.checked_add(1)?;
    }
}

/// Loads [`HalyardOptions`] from a Cargo.toml text content with layered overrides.
/// If an env var is specified, like `HALYARD_ENV` (or the legacy `LEPTOS_ENV`),
/// it will override a setting in the file.
///
/// The settings are read from a `[package.metadata.halyard]` or
/// `[[workspace.metadata.halyard]]` section; the legacy `[package.metadata.leptos]`
/// / `[[workspace.metadata.leptos]]` section names are accepted as a fallback
/// so that existing `cargo-leptos` projects keep working.
///
/// # Errors
///
/// This function will return an error if either:
/// - config section was not found;
/// - failed to deserialize the config section.
pub fn get_config_from_str(
    text: &str,
) -> Result<HalyardOptions, HalyardConfigError> {
    let (metadata_name, (newlines, section_text)) = [
        "[package.metadata.halyard]",
        "[[workspace.metadata.halyard]]",
        // legacy section names
        "[package.metadata.leptos]",
        "[[workspace.metadata.leptos]]",
    ]
    .iter()
    .find_map(|section| {
        find_line_starting_with(text, section).map(|found| (section, found))
    })
    .ok_or(HalyardConfigError::ConfigSectionNotFound)?;

    // so that serde error messages have right line number
    let input = "\n".repeat(newlines) + section_text;
    // so the settings will be interpreted as root level settings
    let toml = input.replace(metadata_name, "");
    let settings = Config::builder()
        // Read the "default" configuration file
        .add_source(File::from_str(&toml, FileFormat::Toml))
        // Layer on the environment-specific values.
        // Legacy `LEPTOS_*` variables first, then `HALYARD_*` so the latter win.
        // E.g. `HALYARD_RELOAD_PORT=5001 would set `HalyardOptions.reload_port`
        .add_source(
            config::Environment::with_prefix(LEGACY_ENV_PREFIX)
                .convert_case(Case::Kebab),
        )
        .add_source(
            config::Environment::with_prefix(ENV_PREFIX)
                .convert_case(Case::Kebab),
        )
        .build()?;

    settings
        .try_deserialize()
        .map_err(|e| HalyardConfigError::ConfigError(e.to_string()))
}

/// Loads [`HalyardOptions`] from a Cargo.toml with layered overrides. If an env var is specified, like `HALYARD_ENV`,
/// it will override a setting in the file. It takes in an optional path to a Cargo.toml file. If None is provided,
/// you'll need to set the options as environment variables or rely on the defaults. This is the preferred
/// approach for cargo-halyard. If Some("./Cargo.toml") is provided, Halyard will read in the settings itself. This
/// option currently does not allow dashes in file or folder names, as all dashes become underscores
///
/// # Errors
///
/// See [`get_config_from_file`] & [`get_config_from_env`]
pub fn get_configuration(
    path: Option<&str>,
) -> Result<ConfFile, HalyardConfigError> {
    if let Some(path) = path {
        get_config_from_file(path)
    } else {
        get_config_from_env()
    }
}

/// Loads [`HalyardOptions`] from a `Cargo.toml` with layered overrides.
/// Halyard will read in the settings itself.
///
/// This option currently does not allow dashes in file or folder names, as all dashes become underscores.
///
/// # Errors
///
/// This function will return an error if either:
/// - path was not found, or other I/O error has occurred;
/// - [`get_config_from_str`] returned an error.
pub fn get_config_from_file<P: AsRef<Path>>(
    path: P,
) -> Result<ConfFile, HalyardConfigError> {
    let text = fs::read_to_string(path)
        .map_err(|_| HalyardConfigError::ConfigNotFound)?;
    let halyard_options = get_config_from_str(&text)?;
    Ok(ConfFile { halyard_options })
}

/// Loads [`HalyardOptions`] from environment variables or rely on the defaults.
///
/// # Errors
///
/// This function will return an error if it failed to load or parse a relevant environment variable.
pub fn get_config_from_env() -> Result<ConfFile, HalyardConfigError> {
    Ok(ConfFile {
        halyard_options: HalyardOptions::try_from_env()?,
    })
}

#[path = "tests.rs"]
#[cfg(test)]
mod tests;
