[package]
name = "halyard_throw_error"
version = "0.1.0"
publish = ["crates-io"]
authors = ["Greg Johnston"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/cgorski/halyard"
description = "Utilities for wrapping, throwing, and catching errors."
rust-version.workspace = true
edition.workspace = true

[dependencies]
pin-project-lite = { workspace = true, default-features = true }

[dev-dependencies]
anyhow.workspace = true
